services:
  - type: web
    name: reclaim-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.21.0
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        sync: false
